apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  vkp.server: |
    __VKP_PLATFORM_NAMESPACE__.svc.cluster.local:1053 {
      errors
      log . {
        class denial error
      }
      cache 30
      forward . __VKP_DNS_IP__
      reload
    }