apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/version: 0.10.0
  name: prometheus-adapter
  namespace: monitoring
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: prometheus-adapter
          args:
            - --cert-dir=/var/run/serving-cert
            - --config=/etc/adapter/config.yaml
            - --logtostderr=true
            - --metrics-relist-interval=1m
            - --secure-port=6443
            - --prometheus-url=https://metrics-proxy.__VKP_PLATFORM_NAMESPACE__.svc.cluster.local:443
            - --prometheus-client-tls-cert-file=/var/run/secrets/paas.dcas.dev/identity/tls.crt
            - --prometheus-client-tls-key-file=/var/run/secrets/paas.dcas.dev/identity/tls.key
            - --prometheus-ca-file=/var/run/secrets/paas.dcas.dev/identity/ca.crt
          readinessProbe:
            initialDelaySeconds: 5
